version: "3"
services:
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bootdb
    volumes:
      - "/tmp/my_dbdata_mysql_1:/var/lib/mysql"      

  employee-jdbc:
   build:
     context: .
     dockerfile: spring.dockerfile
   ports:
      - "8080:8080"
   networks:
      - employee-mysql
   depends_on:
      - mysqldb
 

networks:
  employee-mysql:
  
  
  
  
  
  
  